### ISSUE TITLE
Failed uploads

### ISSUE THREAD

**Issue by Skippern** [mapillary/mapillary_tools#104]
Files that have failed for obvious reasons, such as missing EXIF tags should be moved to the failed folder which the already creates. 

Files failing for problems with internet connection or similar should not be affected by this.

**Comment by jernejaMislej** [comment]
Hi sorry for not getting back earlier.
We have released a new version of the tools, more information on usage in [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md). We have improved the logging, so you will now be able to see whether an upload is failing due to connection issues or missing EXIF tags. 
Hopefully usage will be smoother, if not please let us know
