### ISSUE TITLE
upload.py fails to upload images taken with 3.50 android app

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_tools#153]
```
python upload.py /mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/LEGACY_CAM_0/2017_04_26_16_38_55_723/
Uploading 0 images with valid mapillary tags (Skipping 1545)
Done uploading 0 images.
```

this is rather pressing at the web-uploader for this sequence just ends in **Aww Snap!**, the uploader in the app is borked and I have some much larger sequences to go...

**Comment by sorcrosc** [comment]
For what I have seen pictures from recent app versions don't have mapillary tags anymore.
I am using upload_with_authentication.py

**Comment by mprins** [comment]
it seems direction is missing from the exif tags as well

**Comment by peterneubauer** [comment]
Do you have the GPX file for that sequence too? You should be using `python geotag_from_gpx.py path-to-images/ gpx_file --time-offset [time_offset]` so the images can be properly interpolated,a and then upload them. If you give me only 3 files and the GPX file I can try it for you.  https://github.com/mapillary/mapillary_tools/tree/master/python

**Comment by mprins** [comment]
Not sure why I would need to use the gpx as images have lat/lon from the app (but direction is missing)



attached is the first part of a sequence I shot this morning (using 3.55); this was uploaded though the app an I have just received the "Your Mapillary photos are now published" notification for this [sequence](http://links.mapillary.com/wf/click?upn=SYm2Yy25nY5jqeAJPK2dL29rff3pydlFfOroPZm5iUiMELWwBK9XoCYCr6ACcAcQyk5E5p0DMqH4JlbeSg7mz2gSlca3NdSaoQil8v7C-2BaKGIgaPysORmZxYn6I8bSOPJd5oYGSCtbRTAK8cNGAL5uDQApsHfjhFtHOaaVXeh8AW-2FUWatQl6-2BAj1dt5r3ULrnRw-2BLC9vCFNIQtchnxffjCayaXHJL4e3zyX02dzVd4TCQRpCzFToI3Pktr0DMM82_50k5pea1VwvjYE957hRsfgD-2FWMDGtGRnNl75i12vLuYXeFCfLVs4E2KP6qvKyFDKD6ep-2BUvxLjZP9YQkT9OsbZ5KnU50psGDkXhj-2F8yz86LXRrIZCGLgZQeWcov-2FRE-2FjCEBZeODAh2wn-2FFn368uUgxHzKudDHwimoNblo5iySuN3h44jECOS5r3m8Ty8Hi-2B3GLXhTwPcgOXFUZXc-2B8kDk5D5wt-2B4QFR-2B6xswJgkBE65TE2iG9bJOC2Uh99OBj7V3adgzfimndz9kKRd0lFeSXPrcVl7q2RRIFoUUnWu2WF8-3D)

As you can see this fails when just using the app as well... images are just pointing sideways

[2017_05_08_08_21_36_987.zip](https://github.com/mapillary/mapillary_tools/files/983393/2017_05_08_08_21_36_987.zip)

**Comment by mprins** [comment]
![image](https://cloud.githubusercontent.com/assets/1165786/25803859/40b14b8e-33f9-11e7-84d6-99333a41cbb9.png)

**Comment by peterneubauer** [comment]
Hi there, I checked the sequence. It seems it's taken in GMT+1 timezone? So there is a problem with the EXIF timestamps not having any timezone information, and most phones seem to write localtime. This means that the photos will appear to have different times if you change timezone (you might be not in that timezone when uploading the images). In that case, since the timestamps in GPX do have timezones, the images suddenly are not in the GPX time slot anymore.

We are going to change the filenames from localtime to UTC so we can by parsing the time from the filename determine the UTC timestamp of the image.

If you change the timezone of your phone to the timezone where there images were captured, you should see the track on the phone (I changed my phone to London for this screenshot).

Sorry for this - it's really EXIF timezone lacking that is the problem here.

![screenshot_20170509-230341](https://cloud.githubusercontent.com/assets/11977/25875045/cbf158ac-3515-11e7-8b13-6c96a0566ea2.png)

**Comment by mprins** [comment]
exif daytime (e.g..0x9003) is always local timezone, if you want utc you need to use the GPS date / time (0x001D and 0x0007), note that the latter is a rational number.

**Comment by peterneubauer** [comment]
Yeah, that is the problem. We can't rely on the GPS (that is kind of the point of interpolating, and we can't be sure GPS is even there in all images) and the rest of the EXIF is not reliable.

**Comment by peterneubauer** [comment]
However, we can try to read the GPS time first and see if that is available.

**Comment by mprins** [comment]
> If you change the timezone of your phone to the timezone where there images were captured, you should see the track on the phone (I changed my phone to London for this screenshot).

currently I'm in GMT+2 (because Europe, DST), closed the app, I changed to GMT+0 and to GMT+1
in all cases the map in the upload screen remains black even though I'm on wifi backed by a 50GB connection. I remains black in capture mode as well even though the location fix is "good"

**Comment by sorcrosc** [comment]
Actually I am not able to upload any photo neither with upload_with_authentication.py. Photos don't have gps tags. This is what I get:
```
...
Missing required EXIF tag: GPS GPSLongitude for image 2017_07_08_17_01_46_861/2017_07_08_17_02_59_397.jpg
...
```
Is there something wrong in my phone? I guess no, because I have no problems uploading with Mapillary app. So what tool should we use to upload now? 
I also tried geotag_from_gpx.py to add gps tags but I have problems with that. I will file a bug if needed.

**Comment by richlv** [comment]
does the timezone issue also affect the ios/iphone app ? couldn't figure out from this issue

**Comment by peterneubauer** [comment]
No, iOS is not affected, since there images names have been written in UTC from the beginning. We have switched in the next release of Android to include full timezone info into the filename, so this issue will hopefully disappear.

**Comment by richlv** [comment]
great, thanks for the info :)
