### ISSUE TITLE
skip "thumb" files in upload.py

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#171]
upload.py seems to consider all the images. the recent versions of the mobile apps (at least the ios one) also save *-thumb.jpg files, which are not relevant for the upload. this results in messages like these :

    Uploading 24391 images with valid mapillary tags (Skipping 24391)

-thumb.jpg should probably be ignored by upload.py

**Comment by richlv** [comment]
an even better solution would be to detect the matching "thumbnail" files and move them into the success directory - and report on thumbnail files that do not have matching normal file

**Comment by jernejaMislej** [comment]
hi thank you for the suggestion. currently we are not planning to implement such a feature, so all images that are valid geotagged images with the mapillary image description inserted in the image exif will be considered for upload, others are ignored and are not moved around since we do not want to alter users file system structure. if thumb images are a problem, i suggest to just remove them with `rm *thumb.jpg`
