### ISSUE TITLE
HUGE memory usage

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mapillary/mapillary_tools#199]
Resuming an upload with `upload_with_preprocessing.py` consumes 4156,7 MB of memory and pc becomes unresponsive ...

**Comment by ybkuang** [comment]
@Alessandro-Barbieri we are taking a look at optimizing the processing part of the script. Sorry for the inconveniences.

**Comment by ybkuang** [comment]
@Alessandro-Barbieri By the way, how many images were you uploading?

**Comment by Alessandro-Barbieri** [comment]
More than 1000, didn't remember

**Comment by jernejaMislej** [comment]
hi, just letting you know we have released a new version of the tools. Optimizing the processing part is still work in progress, so it would be great if you could try the new tools and give us feedback on the performance. Instructions and details in the [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md)
since the script for which this issue was opened is no longer available I will close this issue eventually. If you happen to experience similar issues with the new tools, please open a new issue.
