### ISSUE TITLE
incorrect sequence grouping with interrupted `upload_with_authentication.py`?

### ISSUE THREAD

**Issue by katrinhumal** [mapillary/mapillary_tools#220]
@danbjoseph commented on [Mon Feb 12 2018](https://github.com/mapillary/mapillary_issues/issues/2865)

Ran the following on folder with a lot of pictures.
1. `python remove_duplicates.py ~/Desktop/mapillaries/forprocessing/ ~/Desktop/mapillaries/dups`
2. `python sequence_split.py ~/Desktop/mapillaries/forprocessing/ 50 60`
3. `find /Users/danbjoseph/Desktop/mapillaries/forprocessing -mindepth 1 -type d -print0 | xargs -L 1 -0 -P 10 ./upload_with_authentication.py --auto_done`

The upload was interrupted and i had to restart step 3. Some of the resulting sequences on the site have random clumps interspersed among another sequence. If `upload_with_authentication.py` is interrupted/restarted does it start a new sequence with the remaining images? As opposed to using `add_mapillary_tag_from_exif.py` which will assign all the images a sequence id so that no matter if you upload them in multiple chunks, they'll be correctly associated on the server?

![screen shot 2018-02-12 at 12 57 24 pm](https://user-images.githubusercontent.com/4806884/36111635-cf061f90-0ff4-11e8-84d7-62b83a709d37.png)
![screen shot 2018-02-12 at 12 57 52 pm](https://user-images.githubusercontent.com/4806884/36111636-cf08265a-0ff4-11e8-8ba3-0237b826a3de.png)

example sequences in above screenshots:
`7aLfnWJ_CNfqmR65I-yh-w` and `MQA97NfD9RK2K4r4eQDN_w`
(but also happened in other sequences in the same area submitted by user `danbjoseph`)

---

@katrinhumal commented on [Tue Feb 13 2018](https://github.com/mapillary/mapillary_issues/issues/2865#issuecomment-365268959)

@danbjoseph I'm moving this to the mapillary_tools repo. I know it looks a bit deserted lately but we'll pick it up there!

**Comment by katrinhumal** [comment]
@ybkuang or @jernejaMislej Can you please take a look?

**Comment by jernejaMislej** [comment]
thanks @katrinhumal 
@ybkuang if you already have any idea can you let me know all you can on this before i check it out myself, running low on time this week

**Comment by ybkuang** [comment]
@danbjoseph Thanks for reporting this and sorry for the late reply. To handle the sequence issues, it is better to use the `upload_with_preprocessing.py` script. This script has built-in options of removing duplicates and sequence split. It also records the sequence information on the side, so if the upload process gets interrupted, images will still be in the original sequence.

**Comment by danbjoseph** [comment]
so with `python upload_with_preprocessing.py --remove_duplicates path-to-images/`
the sequence [cutoff defaults](https://github.com/mapillary/mapillary_tools/blob/master/python/upload_with_preprocessing.py#L71) with the above are 600m and 60 seconds?
the default duplicate distance with the above is [`0.1`](https://github.com/mapillary/mapillary_tools/blob/master/python/upload_with_preprocessing.py#L79)? 
but the default of `remove_duplicates.py` is [4 meters](https://github.com/mapillary/mapillary_tools/blob/master/python/remove_duplicates.py#L303)?

can you provide an example on how to modify the parameters when running `upload_with_preprocessing.py`?

"records the sequence information on the side" means saved to a file somewhere? and by "interrupted" you mean if the script is terminated and restarted?

**Comment by ybkuang** [comment]
Example params:
```
python upload_with_preprocessing.py [path-to-images] --remove_duplicates --duplicate_distance 0.1 --cutoff_distance 100
```
This will 
- remove any duplicates if the consecutive images are less than 0.1 meter apart 
- split images to sequences if the consecutive images are more than 100 meters apart 

> "records the sequence information on the side" means saved to a file somewhere? 

yes. there is a log file storing the information.

> and by "interrupted" you mean if the script is terminated and restarted?

yes.

**Comment by danbjoseph** [comment]
awesome, thanks so much!

**Comment by jernejaMislej** [comment]
hi @danbjoseph  just letting you know we have released a new version of the tools, which now have one executable to run all the tools needed to upload images to Mapillary, including advanced tools and/or advanced arguments that handle sequence grouping and duplicates. Please try to use the new tools, instructions and details in the [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md) and let me know if you have any more issues, otherwise i will close this

**Comment by danbjoseph** [comment]
so instead of...
```
find ~/Desktop/mapillaries/forprocessing -mindepth 1 -type d -print0 | xargs -P 5 -0 -I {} python remove_duplicates.py -d 0.5 {} ~/Desktop/dups 

find ~/Desktop/mapillaries/forprocessing -mindepth 1 -type d -print0 | xargs -P 5 -0 -I {} python sequence_split.py {} 50 60

export MAPILLARY_USERNAME=danbjoseph 
export MAPILLARY_EMAIL=myemail@email.com 
export MAPILLARY_PASSWORD=mypassword

find ~/Desktop/mapillaries/forprocessing -mindepth 2 -type d -print0 | xargs -P 5 -0 -I {} python add_mapillary_tag_from_exif.py {}

find ~/Desktop/mapillaries/forprocessing -mindepth 2 -type d -print0 | xargs -P 5 -0 -I {} python upload.py {}
```
i can instead just run the following?
```
mapillary_tools process_and_upload --import_path "~/Desktop/mapillaries/forprocessing" --user_name "danbjoseph" --advanced --cutoff_distance 50 --cutoff_time 60 --flag_duplicates --duplicate_distance 0.5 --verbose --rerun
```

from the documentation it's not clear to me where in the command the `--advanced` flag should be placed (if it matters)? if it prompts you for your mapillary username and password upon running? also, it would be helpful to have all the possible parameter flags listed in one place in the documentation (instead of spread across various examples).

**Comment by jernejaMislej** [comment]
hi,
yes you only need to run
```
mapillary_tools process_and_upload
```
with required and optional arguments, nothing else
the order of the arguments is not relevant, so `--advanced` can be put anywhere, to see all the advanced arguments in one place:
`mapillary_tools process_and_upload -h` or just `mapillary_tools process -h`
for the authentication part it doesnt matter whether usage is advanced or not, in any case, in every run, it will look for your credentials in your global config file and since it doesnt exist for the first time, you are prompted to enter your info, so they are created and used automatically in further tool usage

**Comment by danbjoseph** [comment]
terrific. thanks.
