### ISSUE TITLE
incorrect README.md > upload_with_preprocessing.py > env. vars set

### ISSUE THREAD

**Issue by ProBackup-nl** [mapillary/mapillary_tools#226]
### Basic information
* Version: `?` 
* System: `Mac OS X 10.9.5 + zsh shell`
* Capture Device: `n/a`

### Steps to reproduce behavior

 1. read README.md for upload_with_preprocessing.py
 2. it states: 

> Requires environment variables set: MAPILLARY_USERNAME, MAPILLARY_PERMISSION_HASH, MAPILLARY_SIGNATURE_HASH from

 3. define these 3
 4. check with `echo $VAR` that each one is set correct
 5. run `./upload_with_preprocessing.py`

### Expected behavior
No error

### Actual behavior

> You are missing one of the environment variables MAPILLARY_USERNAME, MAPILLARY_EMAIL, MAPILLARY_PASSWORD, MAPILLARY_PERMISSION_HASH or MAPILLARY_SIGNATURE_HASH. These are required.

Even with all 5 set (not exported), this error message still occurs.

**Comment by jernejaMislej** [comment]
hi @ProBackup-nl 
are you using the latest version of master?
although email and password are not required for image preprocessing, they are required for authentication when uploading. have you tried with all 5 exported?
i apologize for the inconvenience, we are working on improving the authentication process to avoid exporting all these variables and will update the readme when the changes are released

**Comment by ProBackup-nl** [comment]
Have tried with all 5 exported. Still an error.

**Comment by jernejaMislej** [comment]
hi, just letting you know we have released a new version of the tools, where authentication is made simpler and easier, so only the user name has to be specified as an argument and nothing needs to be exported in the os environment. Please try to use the new tools, instructions and details in the [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md) and let me know if you have any more issues, otherwise i will close this
