### ISSUE TITLE
please provide scripts that are Python 3.x compatible

### ISSUE THREAD

**Issue by pleabargain** [mapillary/mapillary_tools#227]
upload_with_preprocessing.py is still python 2.x

Please provide scripts that use python 3.x

**Comment by jernejaMislej** [comment]
hi,
we are working on an improved version of the import tools and plan to make it python 3 compatible.
we will let you know as soon as it is available, thank you for the patience

**Comment by realchrisolin** [comment]
Any update on this? It's been nearly a year and I don't see any branches that are an intuitively obvious Python3 rewrite.

**Comment by richlv** [comment]
"pip" now warns:

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.

**Comment by KAMI911** [comment]
I am still interested in updated version for python 3.5 or newer.

**Comment by musuruan** [comment]
Python 2 will be discontinued on January 1, 2020. This means main distributions will stop supporting it. For example, python2 package and all its subpackages have already been removed from Fedora 32 (i.e. the next Fedora release due to be distributed on April 21, 2020). It is urgent to have mapillary_tools migrated to python3.

**Comment by scaidermern** [comment]
The same on Debian. The next _stable_ version (bullseye) won't have support for python 2 any more. This is already the case for the current Debian _testing_ version (python-pip has already been dropped, for example).

Please make mapillary_tools compatible with python 3.

**Comment by andrewharvey** [comment]
I'm running Debian unstable and python-pip is no longer available only python3-pip, when I do `pip3 install .` I get `ERROR: Package 'mapillary-tools' requires a different Python: 3.8.3 not in '>=2.7.0,<3.0.0'`. Anyone know how to install mapillary_tools on Debian sid?

**Comment by scaidermern** [comment]
> I'm running Debian unstable and python-pip is no longer available only python3-pip, when I do `pip3 install .` I get `ERROR: Package 'mapillary-tools' requires a different Python: 3.8.3 not in '>=2.7.0,<3.0.0'`. Anyone know how to install mapillary_tools on Debian sid?

I ran into the same problem while trying to update mapillary-tools to the latest version. Luckily I already hat a copy of mapillary-tools installed which still works. Upgrading/Reinstallation seems to be no longer possible on Debian testing or unstable, though.

**Comment by musuruan** [comment]
Fedora 32 was released on April, 28th. It only provides python3. Now it is no longer possible to run mapillary-tools.

**Comment by andrewharvey** [comment]
> I ran into the same problem while trying to update mapillary-tools to the latest version. Luckily I already had a copy of mapillary-tools installed which still works. Upgrading/Reinstallation seems to be no longer possible on Debian testing or unstable, though.

Yeah I went through my system and cleared out any old local python packages, it was after I did this that mapillary_tools broke and now I seem to be stuck.

**Comment by andrewharvey** [comment]
A workaround could be to run it with docker, but after an hour of trying to get docker containers running i give up. If anyone else knows how to get a docker container up, install pip packages and mount a local directory, I think that would be a good workaround.

**Comment by giocomai** [comment]
Following up on @andrewharvey 's suggestion, here is a Docker-based solution. 

First, create the folders that you will share with the Docker container:

```
mkdir mapillary
mkdir mapillary/pics
mkdir mapillary/config
```

You will copy the pics you want to upload in the `pics` subfolder, while the `config` folder is needed for storing authentication details. 

Then run a Docker container with pre-installed `mapillary-tools` with the following:

```
docker run -t -i \
 -v ~/mapillary/pics:/pics:Z \
 -v ~/mapillary/config:/root/.config/:Z \
  giocomai/mapillary_tools /bin/bash
```
This should download from Docker hub the container with mapillary_tools preinstalled that I have created (find the full Dockerfile if you want to build it yourself at the bottom of this post, ideally the nice folks at Mapillary would provide it themselves). 

When you run this, you will find yourself on the terminal inside the container. 

Now is the time to authenticate with:

`mapillary_tools --advanced authenticate`

Insert your credentials, and you're good to go: you are now inside the container and can run commands as you normally would. Keep in mind that inside the Docker, the pics folder is located at `/pics`.

So you can run your usual commands like this:

`mapillary_tools process_and_upload --import_path "/pics"`

You can also exit the container, by giving the command `exit`. 

You're back in your terminal, on your host machine. 

Since your credentials are stored locally, you don't need to authenticate again in the future, and you can start the container and start uploading pictures with a single command, like this:

```
docker run -t -i \
 -v ~/mapillary/pics:/pics:Z \
 -v ~/mapillary/config:/root/.config/:Z \
  giocomai/mapillary_tools \
  mapillary_tools process_and_upload \
  --import_path "/pics" \
  --user_name "insert_your_mapillary_user_name_here"
```

Of course you can specify the relevant subfolder (e.g. "/pics/new_pics").

If you're on some recent Fedora, you may want to use `podman` instead of `docker`, and things should work just as well. 

Hope this helps.

Here's the full Dockerfile I used if you prefer to build it locally:

```
FROM debian:9

RUN apt-get update 

RUN apt-get install -y git
RUN apt-get install -y python-dev
RUN apt-get install -y ffmpeg
RUN apt-get install -y python-pip

RUN pip install git+https://github.com/mapillary/Piexif

RUN pip install --upgrade git+https://github.com/mapillary/mapillary_tools

RUN mkdir /mapillary_tools
RUN mkdir /root/.config/
```

**Comment by fgouget** [comment]
The Travis continuous integration on GitHub also requires Python 3 which means every pull request now gets an error:

| pip 20.1.1 from /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip (python 3.6)
[...]
| ERROR: Package 'mapillary-tools' requires a different Python: 3.6.7 not in '>=2.7.0,<3.0.0'
| The command "eval pip install -r requirements.txt " failed. Retrying, 2 of 3.

My understanding is that pip is a Python 3 shim that just says Python 2 is no longer supported.
This does make continuous integration pretty pointless (and gives the impression mapillary_tools is not maintained anymore :-( ).

**Comment by scaidermern** [comment]
According to the Telegram group there is ongoing development for a new upload framework, eventually replacing mapillary_tools. Unclear though why there is no reaction from the developers here.

**Comment by richlv** [comment]
Mapillary development process going all closed seems to have helped with getting bought, but it did not help the tools for sure :)
Here's to hope that the process will open up again.

**Comment by andrewharvey** [comment]
> According to the Telegram group there is ongoing development for a new upload framework, eventually replacing mapillary_tools. Unclear though why there is no reaction from the developers here.

Where is the Telegram group? I found https://t.me/s/mapillary via a google but it only has a handful of messages around 2018.

**Comment by scaidermern** [comment]
> Where is the Telegram group? I found https://t.me/s/mapillary via a google but it only has a handful of messages around 2018.

See https://t.me/Mapillary_Discussion

**Comment by jfburke3** [comment]
It looks like UnitedRPMs is providing a python2-pip RPM.....

https://fedora.pkgs.org/32/unitedrpms-x86_64/python2-pip-19.1.1-7.fc32.noarch.rpm.html

**Comment by Strubbl** [comment]
Meanwhile, is there any other method to manually upload images via command line?

**Comment by Jakuje** [comment]
> Meanwhile, is there any other method to manually upload images via command line?

Run some old distro with Python2  in VM

This is also discussed in the following issue: https://github.com/mapillary/mapillary_tools/issues/374#issuecomment-720152479

**Comment by ptpt** [comment]
Hi all,

The Python3 port is close to be done. I tested the basic process and upload and it works great. It would be great to have your help to get more tested. The installation is documented here: https://github.com/mapillary/mapillary_tools/tree/fix-upload#package-installation-python3

Thanks!

**Comment by Strubbl** [comment]
Great work and thanks for the testing invitation. In the meantime i have moved to kartaview where i am uploading my photos. Keep going and have fun

**Comment by ptpt** [comment]
`mapillary_tools 0.6.0` with Python3 support is released here https://github.com/mapillary/mapillary_tools/releases/tag/v0.6.0

Thanks all!

**Comment by KAMI911** [comment]
@ptpt , thank you for the release, works well :1st_place_medal:
