### ISSUE TITLE
Upload with Preprocessing - what is MAPILLARY_USERKEY

### ISSUE THREAD

**Issue by 3vivekb** [mapillary/mapillary_tools#229]
I know y'all are updating the scripts - for some reason this script - upload_with_preprocessing.py - asks for the MAPILLARY_USERKEY as an arg but i'm not sure if that is defined anywhere.

**Comment by jernejaMislej** [comment]
hi
sorry for the issues, please pull the new version and try again, it should not ask for it anymore
let me know if you have anymore issues

**Comment by jernejaMislej** [comment]
hi, just letting you know we have released a new version of the tools, where authentication is made simpler and easier, so only the user name has to be specified as an argument. Please try to use the new tools, instructions and details in the [README](https://github.com/mapillary/mapillary_tools/blob/master/README.md) and let me know if you have any more issues, otherwise i will close this
