### ISSUE TITLE
Script fails to write EXIF tags when attempting to geotag images from GPX

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_tools#238]
### Basic information
* Release version: `current master`
* System: `Linux`
* Capture Device: `GoPro Hero 5` 

### Steps to reproduce behavior

 1. Following [this example](https://github.com/mapillary/mapillary_tools#advanced-examples) in the readme, (minus the duplicate flagging) I ran the following command to geotag 530 images from my GoPro because it failed to get a GPS fix when I started capturing:
`mapillary_tools process --import_path 4_wamego --user_name toebee --advanced --geotag_source gpx --geotag_source_path activity_2714382483.gpx --offset_time 5`
 2. The script ran successfully with the following output:
```Running user_process for 530 images, skipping 0 images.
Running import_meta_data_process for 530 images, skipping 0 images.
Running geotag_process for 530 images, skipping 0 images.
Running sequence_process for 530 images, skipping 0 images.
Running upload_params_process for 530 images, skipping 0 images.
Running mapillary_image_description for 530 images, skipping 0 images.
Process done.
```
### Expected behavior
As I understand it, the script is supposed to take my user information and GPX data and tag the 530 image files with the GPS EXIF tags plus the `Image Description` tag where it puts a bunch of Mapillary specific information.

### Actual behavior
Neither the GPS tags nor the `Image Description` were set on the 530 images despite the script output indicating that it had run the geotagging process. The `Image Description` tag still contains the value set by the GoPro.
```
$ exiftool G0045887.JPG | grep "GPS\|Image Description"     
Image Description               : DCIM\250GOPRO\G0045887.JPG
```

### Corresponding data
In the `.mapillary` directory I found the log files for this image. They are all empty except for `import_meta_data_process.json` and `user_process.json`:

import_meta_data_process.json:
```
{
    "MAPDeviceModel": "HERO5 Black", 
    "MAPDeviceMake": "GoPro", 
    "MAPOrientation": 1, 
    "MAPMetaTags": {
        "strings": [
            {
                "value": "0.0.0", 
                "key": "mapillary_tools_version"
            }
        ]
    }
}
```
user_process.json:
```{
    "MAPSettingsUsername": "toebee", 
    "MAPSettingsUserKey": "value_I_assume_is_supposed_to_be_private"
}
```
I have zipped up 10 of the image files plus the GPX file I am trying to use:
[mapillary_sample_geotagging_images.zip](https://github.com/mapillary/mapillary_tools/files/2070899/mapillary_sample_geotagging_images.zip)

### Additional information
I have used simpler versions of the process command successfully to add user data to images that were already geotagged correctly. I have also used it to upload 3 sequences so far.

I am running in a virtualenv with python 2.7.12

**Comment by jernejaMislej** [comment]
Hi, thanks for reporting this and providing images. I will look into it and get back to you.

**Comment by jernejaMislej** [comment]
hi sorry for the late reply.
I checked your sample and the issue is that the image timestamps are out of the time scope of the gpx file.

If running with `--verbose` this information is printed out and I am thinking that maybe it should print out without the verbose flag, since it is not clear from the logs that this is the reason for failure.

Check if you have the right gpx file and if there is a time offset between the gps trace and the image time. Maybe specifying `--local_time` will be enough already.

**Comment by ToeBee** [comment]
Specifying `--local_time` did indeed fix the problem.

The script should definitely say something other than "success" when it fails to perform the action it was told to perform.

I also think it should default to using local time. Both JOSM and the old `geotag_from_gpx.py` Mapillary script had no issues geotagging these photos out of the box. The GoPro's clock was synced via the phone app either that morning or the day before and the pictures were taken in the middle of a nearly 6 hour long bike ride so I had no reason to think the timestamps would be a problem. This should be the default use case but I had to use a feature that isn't even mentioned in the readme to process it.

I am slightly grumpy about the whole script rewrite. I'm sure I will get over it but I liked having dedicated scripts with simple command lines to do specific tasks. The old scripts took a UNIX style approach of "do one thing and do it well" whereas the new uber-script is a Systemd approach of "put all functionality in one place and hide everything you need behind advanced options"

On the other hand, I really should check out the new video processing features. I think I still have a years worth of Biking Across Kansas videos that I never uploaded because the old video uploader was such a pain to use :)

**Comment by jernejaMislej** [comment]
great that its ok now, just make sure the alignment is really correct when placed on the map, since even if the image timestamps are in the scope of the gps trace, it is not necessary they are aligned perfectly

i know it takes some time to get used to the new setup in tools, especially if you were used to the old scripts and everything worked ok for you before. Unfortunately there were issues with the old setup for many users, thats why things needed to be improved. The new tools are far from being optimal and many issues still remain and I am sure some users feel like new issues were introduced, thats why we are working on the next release in which we plan to improve readme as well.

the question what should be the default assumption for image timestamps has been going around for a long time now, we get more or less equal amount of requests for both defaults, local time and utc

**Comment by jernejaMislej** [comment]
hi please install the latest release v0.1.0 and open a new issue in case problems persist
