### ISSUE TITLE
Error, image EXIF could not be written back

### ISSUE THREAD

**Issue by pasqal** [mapillary/mapillary_tools#256]
hi,
I try mapillary tools for the first time this evening.
But I don't know why the "exif could not be written back". I'm on linuxmint and I follow all user guide, I try user mode and root mode.
![mapillary tools errors](https://user-images.githubusercontent.com/41213762/42716587-85fcc306-86fc-11e8-92ac-66212c10c28b.png)
Thx for your help

**Comment by jernejaMislej** [comment]
hi, thanks for reporting this, can you please send a sample of the images to jerneja@mapillary.com

**Comment by jernejaMislej** [comment]
hi, i did not receive any answer, are you still experiencing issues with mapillary tools? otherwise I will close this.

**Comment by jernejaMislej** [comment]
hi, thanks for the image samples
the problem seems to be in the EXIF editor, since i am getting this error when trying to write back the edited EXIF to the image:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mapillary_tools/exif_write.py", line 89, in write
    exif_bytes = piexif.dump(self._ef)
  File "/usr/local/lib/python2.7/dist-packages/piexif/_dump.py", line 91, in dump
    thumbnail = _get_thumbnail(exif_dict["thumbnail"])
  File "/usr/local/lib/python2.7/dist-packages/piexif/_dump.py", line 154, in _get_thumbnail
    segments = split_into_segments(jpeg)
  File "/usr/local/lib/python2.7/dist-packages/piexif/_common.py", line 10, in split_into_segments
    raise InvalidImageDataError("Given data isn't JPEG.")
piexif._exceptions.InvalidImageDataError: Given data isn't JPEG.
```
I will look into this more and check if there is anything I can do in our EXIF editing lib to support this
in the mean time, just to make sure, this is the camera info : 
```
Make                            : WIKO
Camera Model Name               : LENNY3
Software                        : MediaTek Camera Application
```
did you happen to edit the image with any software or other?

**Comment by pasqal** [comment]
hi,

I just transfer from my phone wiko to my hard disk.
Images from Mapillary app.
In the same time, upload in website work perfectly. I don't know why ?

thk for your help
best regards.
Alain

**Comment by jernejaMislej** [comment]
ok thanks for the information,
currently if one wants to process images, then image EXIF needs to be edited. If there are any deviations from the EXIF standards, our EXIF editing library might fail. I will look into and let you know if I can find a solution.
FYI, if you had captured the images with the Mapillary app, all the required image data should already be embedded in the image EXIF and you can run `mapillary_tools upload` directly, which doesnt require image EXIF editing

**Comment by jernejaMislej** [comment]
hi i had a closer look at the image example you have sent and the issue seems to be in the thumbnail of the image, it is really big with irregular segment marker
if it is removed from the image header everything work ok, so i suggest you do that unless you need images to have the thumbnail data in the image header,
to remove thumbnails from image(s) just run this
```
exiftool -thumbnailimage= 2018_07_19_17_13_08_525_+0200.jpg
```
instead of a file name you can also specify entire directory of images
let me know if that works out for you

**Comment by pasqal** [comment]
Hi,
You're a genius. I try on my directory and it's work very well.
thanks a lot.
