### ISSUE TITLE
Feature Request: Move duplicate pictures

### ISSUE THREAD

**Issue by Stefal** [mapillary/mapillary_tools#271]
Hi!

With the new mapillary_tools, the duplicate processing just flag the duplicates pictures and there is no simple way to find them in the folders.
- Usually, I check these duplicates before starting the upload, and I can't do it anymore
- I always keep all my images, but I don't need to backup the duplicates. Now I can't delete them.

I'd like an option to move the duplicates in another subfolder.

**Comment by jernejaMislej** [comment]
Hi, I m on vacation until 10th August with limited access to internet, I will put something together when I get back and notify you.

**Comment by jernejaMislej** [comment]
hi,
we are working on the next release and plan to provide a feature to handle images flagged as duplicated.
We will keep you updated.

**Comment by jernejaMislej** [comment]
Hi,
we have implemented a `post_process` command to be released in the next tools version which will provide this functionality, limited to moving images that were flagged to be duplicates, uploaded and failed upload. Since this is not yet released you can find it [here](https://github.com/mapillary/mapillary_tools/tree/v0.2.0) and install it same as master(instructions in readme), except that you will have to add the branch name as 
```
pip install --upgrade git+https://github.com/mapillary/mapillary_tools@v0.2.0
```

let me know how that works out for you and if it is sufficient

**Comment by jernejaMislej** [comment]
hi, this functionality is now released, please install the latest version
