### ISSUE TITLE
Split large uploads into subfolder

### ISSUE THREAD

**Issue by SchmidL** [mapillary/mapillary_tools#285]
Hi, 

I processed the last they a lot of images (10k+ per initial folder). Unfortunately, the new `mapillary_tools` does not split the large number of images into subfolders and also does not sort them after successful or failed upload. In the old script, it was like that and helped to sort issues during processing and upload.

Will these feature come back?

**Comment by jernejaMislej** [comment]
Hi,
in the new release we try to avoid changing users file system structure as little as possible, since in the past it has caused more issues then benefits. 
Nevertheless we have implemented a `post_process` command to be released in the next tools version which will provide this functionality, limited to moving images that were flagged to be duplicates, uploaded and failed upload. Since this is not yet released you can find it [here](https://github.com/mapillary/mapillary_tools/tree/v0.2.0) and install it same as master(instructions in readme), except that you will have to add the branch name as 
```
pip install --upgrade git+https://github.com/mapillary/mapillary_tools@v0.2.0
```

let me know how that works out for you and if it is sufficient
