### ISSUE TITLE
HTTP 403 errors if processed images are not uploaded immediately

### ISSUE THREAD

**Issue by ToeBee** [mapillary/mapillary_tools#298]
I always process my images separately from the upload process. This allows me to double check things and make minor tweaks. I have found that if I upload immediately after processing, the upload succeeds. But if there is a gap of a few hours between running `mapillary_tools process` and `mapillary_tools upload` then the upload will fail with HTTP 403 errors. The fix is to delete the `.mapillary` directory and re-upload. It seems like some kind of authentication token that expires after a couple of hours is being set on the images and deleting the directory forces it to issue a new one. 

### Basic information
* Release version: `0.2.0`
* System: `Linux`
* Capture Device: `Action Camera`

### Steps to reproduce behavior
```
$ mapillary_tools process --advanced --user_name toebee --geotag_source gpx --local_time --geotag_source_path ../TdW_day2.gpx --offset_time -3596 --import_path 01/
```
[wait a few hours]

    $ mapillary_tools upload --import_path 01/
    Uploading 351 images with valid mapillary tags (Skipping 0)
    Uploading with 5 threads
    HTTP error: HTTP Error 403: Forbidden on G0077316.JPG--------] 1.4% ... 346 images left.
    HTTP error: HTTP Error 403: Forbidden on G0077319.JPG
    HTTP error: HTTP Error 403: Forbidden on G0077317.JPG
    HTTP error: HTTP Error 403: Forbidden on G0077320.JPG
    ^C
    BREAK: Stopping upload.

    $ rm -rf 01/.mapillary/

    $ mapillary_tools upload --import_path 01/
    Uploading 351 images with valid mapillary tags (Skipping 0)
    Uploading with 5 threads
    Done uploading 351 images.===================================] 100.0% ... 0 images left..
    No post processing action specified.

**Comment by ToeBee** [comment]
Now I'm not sure if the "wait a few hours" step is needed. My uploads tonight failed pretty much right away after processing

**Comment by jernejaMislej** [comment]
hi,
since the upload was successful on 1.4% of images, there seems to be no issues with your credentials, but 
you can still try to re-authenticate by running the `authenticate` command
```
mapillary_tools authenticate --advanced --user_name "user name"
```
and then make sure you have a good network connection. often these issues occur due to network issues, in such cases you can rerun the upload command as many times as needed to complete the upload and ignore the error messages
in case you have a good network connection and none of the images are uploaded, ie you get error messages at 0% upload, let me know and i ll help you investigate the issue more
if your network connection is good and you

**Comment by ToeBee** [comment]
No images were successfully uploaded. The progress bar counts images that are still in the process of uploading. Since it uses 5 threads by default, 5/351 = 0.014. So that's the only reason it says 1.4% complete.

There are also no network problems. This is consistent. I have to delete the `.mapillary` directory **every** time I upload a directory. And every time after I delete it, the upload succeeds with no errors. I have done this dozens of times over the last couple of days as I try to get images from a summer bike tour finally uploaded. Gotta defend my status as #1 uploader in Wyoming from the challenges of @cbeddow :D

**Comment by ToeBee** [comment]
I just sent a dropbox link to the support email with a directory in the state that is generating 403 errors.

**Comment by jernejaMislej** [comment]
ok thank you @ToeBee . did you try to run the authenticate command?
```
mapillary_tools authenticate --advanced --user_name "user name"
```
it could be that you dont have the right authentication credentials stored in your config

**Comment by ToeBee** [comment]
I just tried this and it still failed to upload. Maybe I have to run that batch through the processing step again? But if it is something in my global config, why would deleting the `.mapillary` directory in the upload folder fix it? After I delete the directory, the upload process must use either something in the EXIF tag of the individual images (maybe `MAPSettingsUserKey`?) which would have been set from the global config in the first place or the upload process is pulling directly from the global config.

**Comment by ToeBee** [comment]
It looks like re-authenticating has fixed the problem, but only for sequences where I ran a `process` step after re-authenticating. Which makes sense. So I guess I just some kind of bad token in my config file but somehow deleting the `.mapillary` directory got around that problem? I'm still not quite sure on the details there because these images *were* processed with the script and had the Mapillary EXIF tags set from the config file. So somehow they didn't work when uploading one way but did work another way. Are you sure there isn't a security hole there somewhere? :)

**Comment by jernejaMislej** [comment]
great that the authentication was successful now.

yes it can seem a bit weird that by deleting the .mapillary folder you are no longer required  to authenticate. it is because currently the main requirement is that images have the mapillary image description in the image EXIF and since you ran the process before that, they did. 

we do have an extra requirement of authentication for those images that were processed by users with the tools, but that information is kept in the .mapillary folder and if the user deletes it, the upload is carried as if images had the mapillary image description already inserted prior running the tools.

we might change this in the future, so that all uploads will require authentication, even for images that dont require processing with the tools, for example those taken with the mapillary phone app 

thank you very much for the feedback, let me know if you have any more issues

**Comment by ToeBee** [comment]
ok well I guess this issue can be closed then. I will leave your authentication issues for you to figure out :)
