### ISSUE TITLE
Possibility to take picture order in sequence from filename not from exif date created field

### ISSUE THREAD

**Issue by masterofnoroad** [mapillary/mapillary_tools#481]
Unfortunately GoPro 8 black (and later model also as far I know) has a bug in writing correctly timestamp into EXIF.
So when using photo timelapse mode to capture mapillary sequence it results in spider web connections like here:

https://www.mapillary.com/app/?pKey=565916665240076

It would be easy to workaround the gopro bug to upload photos sorted by filename which always is correct, or use GPS timestamp and not EXIF Date Created.

**Comment by GITNE** [comment]
This is GoPro’s *upstream issue*; this should be fixed by GoPro first. Generally speaking, “re‑timestamping” image files from file names or filesystem timestamps is a bad idea.

In the meantime, one workaround for you could be to make sure you drop the `DateTime` Exif tag (or other offending tag) from all of your images. Since, as you are saying, the `GPSDateStamp` and `GPSTimeStamp` Exif tags are present (and correct) then the backend is going to process your images just fine.

@ptpt An option to select the timestamp source based on which one would also be able to update/fix all the other timestamp sources in the image files might indeed be useful. Probably better yet, it may suffice to just create the Mapillary JSON payload in `ImageDescription` based on the option specified timestamp source and leave everything else untouched.
