### ISSUE TITLE
Support direction of movement

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_tools#76]
The photos from my garmin come with direction tagged, but not in the exif tag that is needed

```
[pnorman@pippin ~/osm/photos/20150913]$ exif 01-to_hume/VIRB0003-3.jpg | grep -i 'direct.*|'
Reference for direct|T
Direction of Movemen|321.234752
GPS Image Direction |T
GPS Image Direction |314.3 <- from interpolate script, not present originally
```

It would be nice to be able to use this information

**Comment by jesolem** [comment]
Thanks for this and the other tools issues today. @ybkuang is going to spend some cleanup time with these scripts (much needed!), assigning to him.

**Comment by mprins** [comment]
see also mapillary/mapillary_issues#1323

**Comment by ybkuang** [comment]
@pnorman, do you mean that you cannot upload the photo because of the missing direction or?

We currently require
 - GPS
 - Capture Time
 - Image Orientation (e.g. portrait or landscape)

We might remove the requirement for Image Orientation in the near future. 

@mprins We will add support for direction of movement later.

**Comment by pnorman** [comment]
Fixed some missing text in the original issue.

Pictures from the garmin come with Direction of Movement, not GPS Image Direction

**Comment by ybkuang** [comment]
Added parser for GPS Track (corresponding to Direction of GPS movement) in EXIF in the recent update.
