### ISSUE TITLE
do not descend in subdirectories by default

### ISSUE THREAD

**Issue by richlv** [mapillary/mapillary_tools#81]
it would great if all tools by default would only operate on the contents of the current directory and subdirs would require a flag.

so many times i have uploaded a sequence, upload script has stalled and i resume it with the same sequence... for it to descend in the "success" directory. arrrgh.

or review images in josm, fix their location and compass direction, then spot that some have missing tags. move reviewed images in a 'tmp' subdirectory, run the script to assign location & direction to the remaining images... and it descends in my 'tmp' and nukes all the work.

even knowing about this, i have this problem so very often. it ends up in worse uploads from me, as in some cases i have been unwilling to redo all the manual cleanup.

**Comment by ybkuang** [comment]
@richlv We are working on scripts with smoother workflow. Will take this into consideration in the flow!

**Comment by richlv** [comment]
in perl this time ?
(joking, joking... glad to hear the scripts getting some attention :) )

**Comment by naoliv** [comment]
Nice... now I have one sequence that I didn't want uploaded because this "feature" is enabled by default.

**Comment by ybkuang** [comment]
@naoliv Hi, subfolders are currently not skipped by default. Which script are you using? upload.py or upload_with_authentication?

**Comment by naoliv** [comment]
`upload.py`
It should be disabled by default :-/

**Comment by ybkuang** [comment]
@naoliv Yes. We can change that. But since you were uploading the photos from the app, it does not matter since the sequence id is encoded in the exif.

**Comment by naoliv** [comment]
I didn't use the app to upload, but `upload.py` (I prefer it instead Mapillary, since I can review all the pics before in my computer).

The problem here is that I had one subdir with pics that shouldn't be uploaded and the script, by default, is recursing all subdirs.
Pics in this subfolder were all taken with Mapillary too (and thus they were all valid and accepted).

To avoid other incidents like this one and to make the behavior consistent with the usage message ("Use from command line as: python upload.py path", ie, it doesn't say that it will go through every dir inside the path), recursing all subdirs should be disable by default.

**Comment by ybkuang** [comment]
@naoliv Thanks for the details. Sorry for being unclear. 

What I wanted to say is that, since you were uploading the photos taken with the Mapillary app, it should not matter if you use `upload.py` to upload photos from different sequences (in different `subfolders`). This is because in the Mapillary app, we encode the sequence ids in the exif of the photos which are used in the processing to ensure photos are in their own sequences. 

There could be something else that are causing this issue. 

But I agree that we should disable recursing subdirs by default. Will fix that soon.

**Comment by naoliv** [comment]
Oh, right. Sorry to misunderstand :-)
Thanks!
