### ISSUE TITLE
Adjust for offset in time of geotagged images

### ISSUE THREAD

**Issue by pnorman** [mapillary/mapillary_tools#86]
The Garmin VIRB XE will sometimes produce images which haverecorded GPS coordinates as if there was an offset between a camera clock and a GPS clock. As an example, http://www.mapillary.com/map/im/KrEYYVBPKEqAJs2J3iZuIw and nearby photos on the same sequence are off in position by about 7 seconds along the sequence.

It would be useful to be able to adjust for this offset.

Photos with a problem like this can easily be created by GPX correlating with an incorrect clock offset.

**Comment by ybkuang** [comment]
@pnorman If you get a GPX file from Garmin VIRB XE, you can use geotag_from_gpx.py for processing https://github.com/mapillary/mapillary_tools/blob/master/python/geotag_from_gpx.py#l198 with the -time_offset option. If not, we need to figure out something else.

**Comment by pnorman** [comment]
> @pnorman If you get a GPX file from Garmin VIRB XE, you can use geotag_from_gpx.py for processing https://github.com/mapillary/mapillary_tools/blob/master/python/geotag_from_gpx.py#l198 with the -time_offset option. If not, we need to figure out something else.

I haven't found one. I might be able to make one from the photos, and wrote some software to do this in the past.

**Comment by ybkuang** [comment]
@pnorman Just so that I understand correctly, the GPS info with time offset are in the exif of the photos?

**Comment by pnorman** [comment]
> @pnorman Just so that I understand correctly, the GPS info with time offset are in the exif of the photos?

The exif of the photos have a time. I do not know if this time was from the GPS or a different clock on the device.

**Comment by jernejaMislej** [comment]
hi,
since this issue was opened we have experienced a few more cases where this feature would be useful and are therefore planning to implement it in one of the future releases. 
We will keep you updated on the progress.

**Comment by jernejaMislej** [comment]
hi, we have implemented this functionality on this [branch](https://github.com/mapillary/mapillary_tools/tree/v0.3.0), which is planned for the next release
you can test it by installing the branch instead of master
```
pip install --upgrade git+https://github.com/mapillary/mapillary_tools@v0.3.0
```
to specify time offset you need to pass the following args to your cl for process : `--advanced --offset_time "offset in seconds"`, ie 
```
mapillary_tools process --advanced --import_path "path/to/images" --user_name "your user name" --offset_time "offset in seconds" 
```
since the time is overwritten, you can keep the original by adding arg `--keep_original` which will store the processed images in `.mapillary/processed_images` in your `import_path`

let me know if you have any issues, if this add on resolved your initial issue please close it

**Comment by jernejaMislej** [comment]
hi this is now released
note that with the new release you have to specify an additional argument to overwrite the rest of EXIF tags besides Image Description `--advanced --overwrite_all_EXIF_tags`
closing this
